### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Mo7amedSMahdi** [Mo7amedSMahdi/art-institute-chicago-api#23]
Hello everyone,
we are very excited🤩🎉 to start working on our project with new things to learn about Kanban boards and GitHub Projects.

So let me introduce ourselves to you, We are a team of three students Mohammed Salah(Medo), Melaku Shiferaw and Basit Korede.
here is the link to our project 
https://github.com/Mo7amedSMahdi/art-institute-chicago-api/projects/1
Thanks in advance.

**Comment by andersonlebon** [comment]
### Hi @team

Good job so far! I know you have worked hard on making this milestone There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Required Changes ♻️

- [ ] Kindly would you please assign all tasks [C] to Team member C as now these tasks are not assigned to anyone

![image](https://user-images.githubusercontent.com/65068771/163953515-ed374ee2-fbe5-48c8-bd6e-0b562d86e4f1.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @BasitKorede, @Melaku05, and @Mo7amedSMahdi 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Github inline comments feature is used properly.
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
